name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os:
          - ubuntu-slim
          - ubuntu-22.04
          - windows-2022
          - macos-15-intel
          - macos-15
        aqt-setup-python:
          - true
          - false
        python-ver:
          - 3.13
          - 3.14
          - ''
        exclude:
          - aqt-setup-python: true
            python-ver: 3.14
          - aqt-setup-python: true
            python-ver: 3.13
    steps:
      - name: Setup Python
        if: ${{ !matrix.aqt-setup-python && matrix.python-ver != '' }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-ver }}

      - uses: pzhlkj6612/forked-install-qt-action@06bc6c4bcd6fe5dc4da95515acd692b01601a8fc
        with:
          setup-python: ${{ matrix.aqt-setup-python }}
